### ISSUE TITLE
adding a LibPdInstance next to an Audio Listener crashes Unity 2021.1

### ISSUE THREAD

**Issue by RVirmoors** [LibPdIntegration/LibPdIntegration#23]
if the game object you add LibPdInstance to already has an Audio Listener component (or vice versa), then the Unity editor immediately crashes

you can easily reproduce this by attempting to add LibPdInstance to the Main Camera in a new project, for example

this appears to only happen on Unity 2021.1 -- I couldn't reproduce it in Unity 2019.4

i'm on Windows 10, using LibPdIntegration 2.1.1

**Comment by NiallMoody** [comment]
Oof. Yeah, I've been able to verify that myself. For me it's not just happening when adding a LibPdInstance to a game object with an AudioListener, it's happening whenever Unity runs the audio thread with a LibPdInstance active (this suggests adding a LibPdInstance to an AudioListener in the editor triggers Unity to run the audio thread for it even though the game isn't running, which seems weird to me).

Anyway, the crash is happening in libpd, at [line 177 of z_libpd.c](https://github.com/libpd/libpd/blob/2a82837b55112e92883642d50e322d78d6977d0e/libpd_wrapper/z_libpd.c#L177). That's where libpd locks its mutex before performing any audio operations. It's not ideal to be locking mutexes on the audio thread, but it's not clear to me why that would cause a consistent, repeatable crash.

I'm going to try and chase it up, but in the meantime I'm afraid my recommendation is going to have to be: **don't use Unity 2021.1**.

I think this problem is outside of my control. If I can gather a bit more information I'll try submitting a bug report to Unity, because I don't _think_ it's related to anything in my code, and I don't see anything obviously wrong with the libpd code.

**Comment by NiallMoody** [comment]
Wait, no. Actually that _was_ a bug in my code. It turns out what was actually happening was LibPdInstance wasn't checking whether a patch had been loaded before calling some libpd functions that expect the patch to have been loaded.

So Unity was running the audio thread on LibPdInstance as soon as you added the component to the game object, and libpd was crashing because obviously you hadn't had time to assign a Pd patch to it yet.

It's still not clear to me why Unity is running the audio thread on a newly created component in the editor, but the crash is very much my fault for not checking that a valid patch has been loaded before calling libpd functions.

I've uploaded a fix to the repo. You can either pull the latest version, or download the [2.1.2](https://github.com/LibPdIntegration/LibPdIntegration/releases/tag/v2.1.2) release.

If you can let me know if that fixes it for you, I'll close this issue.

**Comment by RVirmoors** [comment]
awesome, thanks for looking into it and fixing it so quickly.

The scene seems to run correctly now, but I still get an error: GameObject has multiple AudioSources and/or AudioListeners attached. While built-in filters like lowpass are instantiated separately, the custom script DSP filter components may only be used by either one AudioSource or AudioListener at a time. In this case the OnAudioFilterRead callback of script LibPdInstance was first attached to a component of type AudioListener on the game object Main Camera after which a component of type AudioSource tried to attach it.

The error goes away (and the pd patch is still audible) if I disable the AudioSource on the Main Camera object.

Again, the same process produces no errors in Unity 2019.4

**Comment by NiallMoody** [comment]
This seems to be a new error message introduced in 2021.1. I've not been able to find it documented anywhere, but I think it's Unity telling you that the engine has no way of knowing whether the LibPdInstance audio filter should be applied to the AudioSource or the AudioListener on that game object. I think basically you're just not supposed to do that.

You get the exact same error if you add 2 AudioSources to a game object and then add a custom audio filter like LibPdInstance.

The simplest solution is to create a child object and put your LibPdInstance/AudioSource on it, so that it's separate from the game object with the AudioListener on it.

I'm going to close this issue as I don't believe it's a problem with LibPdIntegration. I get the same error with any custom audio filter component I try to add to a game object that has both an AudioListener and an AudioSource.

Here's a very simple low pass filter you can use to verify that. I get the exact same error with this as I get with LibPdIntegration:
```c# using UnityEngine;

//Super simple low pass filter test.
public class CustomFilterTest : MonoBehaviour
{
	[Range(0.001f, 1.0f)]
	public float coeff = 0.15f;

	private float[] prev = {0.0f, 0.0f};

	private void OnAudioFilterRead(float[] data, int channels)
	{
		//Assuming stereo audio.
		for(int i=0;i<(data.Length/2);++i)
		{
			data[(i*2)] = prev[0] + ((data[(i*2)] - prev[0]) * coeff);
			prev[0] = data[(i*2)];
			data[(i*2) + 1] = prev[1] + ((data[(i*2) + 1] - prev[1]) * coeff);
			prev[1] = data[(i*2) + 1];
		}
	}
}
```
