### ISSUE TITLE
WebGL build

### ISSUE THREAD

**Issue by LeoPassos** [LibPdIntegration/LibPdIntegration#24]
Is it possible to export a WebGL build with Unity using Pd and LibPdIntegration?

**Comment by axtTOKQf** [comment]
I also wonder that. It gives the same error as when creating for Mac: conflicting versions of libpd. I guess and hope this issue has a solution for WebGL in a way similar to the one for Mac.

**Comment by NiallMoody** [comment]
Sorry, I'm going to close this, as it's already discussed in issue #15. Basically, a WebGL build requires an libpd binary built using emscripten, which I've not attempted to build myself for the reasons outlined in issue #15.

I think ultimately this is all linked to issue #20; in order to support all these extra platforms I'm really going to need help from people who are willing to build and maintain libpd binaries for each platform, as I don't have the capacity to do so myself.
