### ISSUE TITLE
Receiving sent values from instanced versions of the same Pd patch.

### ISSUE THREAD

**Issue by sambilbow** [LibPdIntegration/LibPdIntegration#25]
Hi! I'm loving this project as it's exactly what my project requires to get the audio-end working flexibly!

I'm running into an issue where I need to receive a float value from the patch. After following the LibPd-2-Unity tutorial, I have the following code receiving a float value "volume" from the patch and influencing the scale of the object.
```
public void FloatReceive(string sender, float value)
	{
		if(sender == "volume")
		{
			scaleObject.localScale = new Vector3(0.1f+(value/1f), 0.1f+(value/1f), 0.1f+(value/1f));
		}
	}
```
However, I have two game objects, each with their own LibPdInstance running this single patch, and both are receiving the volume value from the first instance of the patch.

Is this an issue with the way my variables are setup? 
See this video for a short demo of the issue: https://www.youtube.com/watch?v=c_jD0dD6zRg

**Comment by NiallMoody** [comment]
Hi, apologies for the delayed reply. I believe you're seeing this behaviour because libpd gives us a single float callback function for **all** patches, and doesn't distinguish between which patch triggered it. So if you have 2 identical patches both sending a float called "volume", the LibPdIntegration.cs script has no way of knowing which patch sent that float, because the only information libpd gives us is:
1. a float value has been sent, and
2. its name is "volume"

To be honest, I don't know if it's possible to solve this on our end. I think it's a limitation with libpd itself, as (unless I'm missing something) it just doesn't provide the information we would need to distinguish between patches.

If you need to use multiple copies of a single patch for this, the only solution I can think of is to create a unique send name in your c# script, send that name (using **SendSymbol**) to your patch, then use it as the destination for your send object in the patch. So you would end up with something like "volume1", "volume2", etc.

In pd it would be something like this:
![image](https://user-images.githubusercontent.com/21282294/132257911-70965f2c-d28a-45aa-9157-95522d3df38a.png)

Note: I've not had a chance to test this. It might be a wee bit tricky in that I think the Bind function will need to be called _after_ the send object has had its destination set, and I'm not sure if that will happen immediately, or if it only gets updated once libpd has run its processing loop once.

It is also very much a hack, but I'm afraid I can't see another way to do it unless the libpd developers update their public-facing API.

**Comment by sambilbow** [comment]
Hey Niall, thanks so much for the reply. I can confirm that this method does indeed work and will cut down tedious development time considerably by being able to keep instance multiple patches from one file and receive their sends separately.

_Testing that the sent volume symbol would work_
![](https://i.imgur.com/KOIZrEo.gif)

_Ordering of Send/Bind Inside the void Start() in the attached C# script_
```     
pdPatch.SendSymbol("volumename","volume2");
pdPatch.Bind("volume2");
```

_The scene in Unity_

https://user-images.githubusercontent.com/31018239/132390647-c2508c57-7bb8-4b04-bb9e-1baaf71ebf39.mp4




I would really appreciate your input on the following if you have time!
- In my envisaged scenario of 200 instances of a Pd patch, the method would still require 1 individualised script per GameObject; telling the attached LibPdInstance which "instance" of the patch it wants to Bind to in the script and receive a value from. This, along with the dragging of individual LibPdInstances, transforms, and scripts required to set up the GameObject would be a lot of work.

- I was wondering if you could envisage a way of using the [$0-name] object/instance naming method in Pd to get around this problem? I had a go and the immediate issue was that receiving the "ID" (whatever "$0" gets assigned at load) is essentially another instanced variable like my initial pursuit of instanced volume values.

- Perhaps to get around this I would have to develop some kind of  "instance manager" GameObject that gathers all of the $0 IDs from instanced patches in the scene. This would require "listening out" for all of the send names in instanced patches.

- I assume this is not possible due to the way you have implemented the explicit naming in the Bind system; but would very much appreciate if this could be confirmed impossible. If so, probably some sort of script would have to be developed to generate C# and GameObject bindings if I wanted to realise my scenario.

**Comment by NiallMoody** [comment]
So I did have a quick look at the possibility of using $0 for this before my initial reply. What I found was that libpd generated the same $0 value for each instance, presumably because each patch was effectively running in its own separate instance of Pd.

You should probably check this yourself, because it may be that I missed something. From my quick test however, it seems $0 values are only unique _within_ an instance of Pd, and in order to make use of Unity's spatialisation we need each patch to run in its own separate instance of Pd.

If I've misunderstood this however, and libpd _does_ provide unique $0s between instances, it's worth pointing out that LibPdIntegration has a GetDollarZero() function that you can call directly to get the $0 for a particular patch; no need to send it from within your Pd patch.

---

Regarding your larger task, I would definitely implement some kind of instance manager to set all this up. And with that many instances, this is probably a task for [Unity's Instantiate function](https://docs.unity3d.com/Manual/InstantiatingPrefabs.html). i.e. create a prefab with the required components and then use your manager to instantiate that prefab throughout the scene. You would still need to set up libpd bindings etc. but that can be done in your manager script each time you create a new instance. I'd imagine the process would be something like the following:
```
int index = 0
For each instance:
  Instantiate prefab
  Send unique volume name to patch (i.e. <name>index)
  Bind to unique volume name
  Increment index
```
You wouldn't actually need $0 for this approach.

I should say that I've never attempted to run 200 Pd patches at once. I wouldn't be surprised if you encounter performance issues with that many simultaneous active patches.

**Comment by sambilbow** [comment]
Thank you so much for your reply. I will have an investigate over the next couple weeks and report back here if thats okay? Could be useful for future repo users.

**Comment by sambilbow** [comment]
### Redescription of desired effect
- [x] 1. One Pd patch, and one script in charge of all the sound generation and parameterisation/visualisation respectively of a GameObject
- [ ] 2. Package this into an instanceable prefab. 
- [ ] 3. Instance many of these prefabs
- [x] 4. Send data to each prefab's Pd patch separately based on hand gestures and other scene variables
- [ ] 5. Receive unique data from each prefab's Pd patch (despite them all using the same patch)

#### I can achieve 2 and 3 with a bit of learning so this issue is mainly about 5. 

---
### Solution
I just stumbled across this solution, came back to this issue and found that its essentially what you pointed me in the direction of! It involves sending the name of the GameObject (which will eventually iterate as they spawn (e.g. object-0, object-1, object-2) over to PureData to act as a kind of psudeo `$0` that Unity can access (because it put it there).

This looks quite similar to the quick fix I did above, but whereas that fix still required a unique script per GameObject, this fix uses the same script and Pure Data patch per GameObject. 

**In Pure Data**
![Screenshot 2021-10-11 at 16 22 43](https://user-images.githubusercontent.com/31018239/136815720-1549524b-150a-4d2e-a81b-0b7f518554db.gif)
 Set up a receive mechanism that stores the GameObject's name and accordingly sets the name of a send object inthe patch



**In Unity/C#**
1. Name the GameObject with indexes (i.e. sphere-id-0, sphere-id-1 etc..)
2. In the script for the GameObject that deals with the Pd patch, do the following  (where `pdPatch` is a variable containing your LibPdInstance)
  i. Send the name of the GameObject over to the receive object you made above.
  `pdPatch.SendSymbol("label",gameObject.name);`
  ii. Bind to the name of the GameObject
  `pdPatch.Bind(gameObject.name);`
  iii. Set up a conditional BangRecieve() function so that the you can make stuff happen only if the bang comes from the patch who's index is equal to your object's name (if you dont do this, you will receive multiple bangs, although unique they will be copied for every `public void BangReceive()`):
  ```
    public void BangReceive(string name)
    {
        // If the name received by the LibPdInstance event equals the object name
        if (name == gameObject.name)
        {
            // Print that you received a bang
            Debug.Log("Received bang from: "+name);
            // One day soon, do some awesome audiovisualisation of the Pd patch in 3D!
        }
    }
  ```

---
### Next steps
I will want to bind to more than just one outgoing message from PureData. I will try doing this by binding to indexed parameters that still use the GameObject's name: `pdPatch.Bind(gameObject.name+"volume")` and set up multiple send objects as the above screenshot shows by using `[list append]` then `[list trim]` so that PureData sends out via an object named `[sphere-id-1volume]` for example.

Eventually I'll tackle building the GameObject naming into a prefab instancer, but the way I see it, this is probably the best fix I can go with for the time being

--- 
### Caveat
A downside is having to set up the new send system with a testing mechanism (since without Unity telling it what the send object is sending to, it doesnt go anywhere). You can see I did this by sending `[sphere-id-0(` to make sure that the mechanism works.
