### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by mxa** [LibPdIntegration/LibPdIntegration#8]
What's missing to add Linux support?
(other than putting the linux libpd binary in the assets)

**Comment by mxa** [comment]
~~Regarding the patch towards an 2018 version of libpd: has there been filed an issue for libpd so that the patch may become obsolete?~~ Ah, now I see the remark it's obsolete.

**Comment by NiallMoody** [comment]
All it should require is a Linux libpd binary in Assets/Plugins. I built the Windows and OSX binaries from [this libpd commit](https://github.com/libpd/libpd/commit/c847512c83de732466f26a2f1a2e4f4fde7aa35f) if you want to ensure you're working from the same version (though I assume that as long as the libpd interface hasn't changed, you'll be fine with a more recent version).

I don't have a Linux setup at the moment and have limited time to work on this, otherwise I'd have built it myself.

**Comment by mxa** [comment]
I dropped an up to date `libpd.so` file into assets and I am getting the following errors:
```

DllNotFoundException: libpd
LibPdInstance.Awake () (at Assets/Scripts/LibPdInstance.cs:525)
```

and

```
DllNotFoundException: libpd
LibPdInstance.SendFloat (System.String receiver, Single val) (at Assets/Scripts/LibPdInstance.cs:796)
(wrapper synchronized) LibPdInstance:SendFloat (string,single)
Proximity2Float.Update () (at Assets/Scripts/Unity2LibPdSceneScripts/Proximity2Float.cs:63)

```

**Comment by mxa** [comment]
Do you think it's related to the newer version of libpd? The error message seems to indicate it can't find the library at all.

**Comment by mxa** [comment]
If i compile libpd for windows and replace the libpd.dll with an up to date one and get the same issue there, that suggests the answer would be yes. Will try.

**Comment by mxa** [comment]
To test, I've compiled an unpatched release tag 0.11.0 of libpd for windows and replaced the binary in the assets. Unity crashes.

**Comment by NiallMoody** [comment]
Okay, I finally had some time to test 0.11.0 on Windows myself (had to add a couple of extra files to the makefile, but I see that you encountered the same issue), and it seemed to work fine for me? I verified it in my test project, here: https://github.com/LibPdIntegration/LibPdIntegrationTests

On Linux I'm in the dark without being able to test it myself (and I don't have time to set up a Linux install at the moment). I have found in the past that Unity can be a bit picky when it comes to build settings for native plugins, so my initial thought is that you might need to modify the libpd build settings so that it will play nice with Unity. Have you built any other Unity plugins on Linux that you could compare makefiles with?

**Comment by NiallMoody** [comment]
Thanks to a generous contributor, this issue is now resolved. If you check the repo you'll see 32-bit and 64-bit Linux binaries in the Plugins folder.

**Comment by mxa** [comment]
Instead of including a linux binary, wouldn't it be better to add libpd as a submodule and build it with a makefile? This way we know what we are loading and how it is compiled. It will be easier to update with a new libpd release then having to guess how the binary was compiled.
